[Desktop Entry]
Type=XSession
Exec=@CMAKE_INSTALL_FULL_LIBEXECDIR@/startplasma-dev.sh -x11
DesktopNames=KDE
Name=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ar]=SonicDE (تطوير, اكس11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[az]=SonicDE (Tərtib mərhələsində olan X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[be]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[bg]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca]=SonicDE (Desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ca@valencia]=SonicDE (desenvolupament, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[cs]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[da]=SonicDE (udvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[de]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[el]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[en_GB]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[eo]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[es]=SonicDE (Desarrollo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[et]=SonicDE (arendus, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[eu]=SonicDE (Garapena, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fi]=SonicDE (kehitys, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[fr]=SonicDE (Développement, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ga]=SonicDE (Forbairt, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[gl]=SonicDE (desenvolvemento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[he]=SonicDE (פיתוח, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[hi]=SonicDE (विकास, एक्स ११ ${CMAKE_INSTALL_FULL_BINDIR})
Name[hu]=SonicDE (Fejlesztői verzió, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ia]=SonicDE (Disveloppamento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[id]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[is]=SonicDE (Þróunarútgáfa, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[it]=SonicDE (Sviluppo, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ja]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ka]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ko]=SonicDE(개발, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[lt]=SonicDE (Plėtojimas, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[lv]=„SonicDE“ (izstrāde, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ml]=SonicDE (വികസനം, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nb]=SonicDE (utvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nl]=SonicDE (Ontwikkeling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[nn]=SonicDE (utvikling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pa]=SonicDE (ਡਿਵੈਲਪਮੈਂਟ, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pl]=SonicDE (Rozwój , X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt]=SonicDE (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[pt_BR]=SonicDE (Desenvolvimento, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ro]=SonicDE (Dezvoltare, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ru]=SonicDE (разрабатываемая версия, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sa]=SonicDE (विकास, X११ ${CMAKE_INSTALL_FULL_BINDIR})
Name[sk]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sl]=SonicDE (Razvoj, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[sv]=SonicDE (utveckling, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ta]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[th]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[tr]=SonicDE (Geliştirme, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[ug]=SonicDE (ئىجادىيەت نەشرى، X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[uk]=SonicDE (Розробка, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[vi]=SonicDE (Phát triển, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[zh_CN]=SonicDE (Development, X11 ${CMAKE_INSTALL_FULL_BINDIR})
Name[zh_TW]=SonicDE (開發版本，X11 ${CMAKE_INSTALL_FULL_BINDIR})
Comment=Sonic Desktop Environment
Comment[ar]=بيئة سطح المكتب سونيك
Comment[az]=Sonic Masa Üstü Mühiti
Comment[be]=Сонік асяроддзе працоўнага стала
Comment[bg]=Соник работна среда
Comment[bs]=Sonic radno okruženje
Comment[ca]=Entorn d'escriptori Sonic
Comment[ca@valencia]=Entorn d'escriptori Sonic
Comment[cs]=Sonic pracovní prostředí
Comment[da]=Sonic skrivebordsmiljø
Comment[de]=Sonic Arbeitsumgebung
Comment[el]=Περιβάλλον επιφάνειας εργασίας Sonic
Comment[en_GB]=Sonic Desktop Environment
Comment[eo]=Sonic Labortablo Ĉirkaŭaĵo
Comment[es]=Entorno de escritorio Sonic
Comment[et]=Sonic töölaud
Comment[eu]=Sonic mahaigain ingurunea
Comment[fi]=Sonic-työpöytäympäristö
Comment[fr]=Environnement de bureau Sonic
Comment[ga]=Timpeallacht Deisce Sonic
Comment[gl]=Ambiente de escritorio Sonic
Comment[he]=סביבת שולחן העבודה סוניק
Comment[hi]=सोनिक डेस्कटॉप वातावरण
Comment[hsb]=Sonic dźěłowe wokolina
Comment[hu]=Sonic asztali környezet
Comment[ia]=Sonic Ambiente de Scriptorio
Comment[id]=Lingkungan Desktop Sonic
Comment[is]=Sonic skjáborðsumhverfi
Comment[it]=Ambiente desktop Sonic
Comment[ja]=Sonic デスクトップ環境
Comment[ka]=Sonic სამუშაო გარემო
Comment[ko]=소닉 데스크톱 환경
Comment[lt]=Sonic darbalaukio aplinka
Comment[lv]=Sonic darbvides vide
Comment[ml]=സോണിക് പണിയിട പരിസ്ഥിതി
Comment[nb]=Sonic skrivebordsmiljø
Comment[nds]=Sonic Schrievdischümgeven
Comment[nl]=Sonic-werkomgeving
Comment[nn]=Sonic skrivebordsmiljø
Comment[pa]=ਸੋਨਿਕ ਡੈਸਕਟਾਪ ਵਾਤਾਵਰਨ
Comment[pl]=Środowisko pulpitu Sonic
Comment[pt]=Ambiente de trabalho Sonic
Comment[pt_BR]=Ambiente de trabalho Sonic
Comment[ro]=Sonic mediu de birou
Comment[ru]=Соник рабочая среда
Comment[sa]=सोनिक् डेस्कटॉप् परिवेशः
Comment[sk]=Sonic pracovné prostredie
Comment[sl]=Sonic namizno okolje
Comment[sr]=Соник радно окружење
Comment[sr@ijekavian]=Соник радно окружење
Comment[sr@ijekavianlatin]=Sonic radno okruženje
Comment[sr@latin]=Sonic radno okruženje
Comment[sv]=Sonic skrivbordsmiljö
Comment[ta]=சோனிக் பணிச்சூழல்
Comment[tg]=Муҳити мизи кории Sonic
Comment[th]=สภาพแวดล้อมเดสก์ท็อป Sonic
Comment[tr]=Sonic masaüstü ortamı
Comment[ug]=Sonic ئۈستەلئۈستى مۇھىتى
Comment[uk]=Сонік середовище робочого столу
Comment[vi]=Môi trường máy tính để bàn Sonic
Comment[zh_CN]=Sonic 桌面环境
Comment[zh_TW]=Sonic 桌面環境
X-KDE-PluginInfo-Version=${PROJECT_VERSION}
